### PR TITLE
25 GitHub activity

### PR DESCRIPTION
**Pull request by skywolff**
finished issue #25,  user story: As an author, I want to pull in my github activity to my “stream”, posts and github activities are also sorted by dates according to the project spec. Formatting could be improved with Markdown.

### CODE REVIEW

**Review by olivaC — CHANGES_REQUESTED** [review]
This works great! Good job! 👍 Do you think we can possibly just add the most recent 5 github activities to the stream? I just noticed that because there's so much github activity that I can't even see posts anymore haha.

**Comment by skywolff** [comment]
only the first 5 recent activities from github is showed now, still ugly... but it's not a priority

**Comment by carrolji** [comment]
I got an error in the index page: SSLError at /index
after adding in my github url

**Comment by skywolff** [comment]
Carlo got that as well, I wasn't able to reproduce, could you guys show me a screen shot? It only says SSLError and nothing else?

**Comment by olivaC** [comment]
Screen Shot 2019-03-27 at 9 37 32 PM

**Comment by olivaC** [comment]
It's happening on ths line in gh_stream.py

```    events = github.Github().get_user(gh_username).get_events()```

**Comment by skywolff** [comment]
So this is a macOS specific issue according to this
https://stackoverflow.com/questions/44316292/ssl-sslerror-tlsv1-alert-protocol-version

I installed requests[security] to the venv, could one of you try it again?

**Comment by olivaC** [comment]
Stupid MacOS. Sorry about that. I found one line that was causing the whole thing to crash and it was unused so i just took it out. I'm going to try this out on my test heroku server now.

**Comment by skywolff** [comment]
sorry I left those lines there because I thought it may be useful in the future, I'll get rid of them

**Comment by olivaC** [comment]
Oh don't worry about removing them. I probably shouldn't have removed it myself, but it was just one line.

**Review by olivaC — APPROVED** [review]
Works on the test server 👍 Go ahead and merge this PR

**Pull request merged**
